//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int RecordId { get; set; }
        public int CartId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ProductId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
