//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int RecordId { get; set; }
        public System.Guid CartId { get; set; }
        public Nullable<int> Customerid { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
