//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Emp_id { get; set; }
        public string Ename { get; set; }
        public string Job { get; set; }
        public Nullable<int> Mgr_id { get; set; }
        public System.DateTime Hiredate { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<int> Com { get; set; }
        public Nullable<int> Dept_no { get; set; }
    
        public virtual DEPT DEPT { get; set; }
    }
}
