//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int emp_no { get; set; }
        public string E_name { get; set; }
        public Nullable<double> Sal { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
    }
}
