// <auto-generated />
namespace MVC_EF_Code_First.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Productconfiguration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Productconfiguration));
        
        string IMigrationMetadata.Id
        {
            get { return "202412300942554_Product configuration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
